// auth
export const SIGNIN = 'SIGNIN';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNOUT = 'SIGNOUT';

export const SHOW_SIGNIN_FORM = 'SHOW_SIGNIN_FORM';
export const SHOW_SIGNUP_FORM = 'SHOW_SIGNUP_FORM';

// user
export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const READ_USER = 'READ_USER';
export const READ_USER_ERROR = 'READ_USER_ERROR';
export const GET_USER_CARDS_NUMBER = 'GET_USER_CARDS_NUMBER';
export const GET_USER_CARDS_NUMBER_ERROR = 'GET_USER_CARDS_NUMBER_ERROR';

// deck
export const GET_DECKLIST = 'GET_DECKLIST';
export const GET_DECKLIST_ERROR = 'GET_DECKLIST_ERROR';
export const CREATE_DECK = 'CREATE_DECK';
export const CREATE_DECK_ERROR = 'CREATE_DECK_ERROR';
export const DELETE_DECK = 'DELETE_DECK';
export const DELETE_DECK_ERROR = 'DELETE_DECK_ERROR';
export const READ_DECK = 'READ_DECK';
export const UPDATE_DECK = 'UPDATE_DECK';
export const UPDATE_DECK_ERROR = 'UPDATE_DECK_ERROR';
export const DECK_SHOW_LOADING = 'DECK_SHOW_LOADING';
export const DECK_HIDE_LOADING = 'DECK_HIDE_LOADING';
export const CLEAR_DECKLIST = 'CLEAR_DECKLIST';
export const CLEAR_READED_DECK = 'CLEAR_READED_DECK';

// card 
export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_ERROR = 'CREATE_CARD_ERROR';
export const GET_CARDLIST = 'GET_CARDLIST';
export const GET_CARDLIST_ERROR = 'GET_CARDLIST_ERROR';
export const UPDATE_CARD = 'UPDATE_CARD';
export const UPDATE_CARD_ERROR = 'UPDATE_CARD_ERROR';
export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_ERROR = 'DELETE_CARD_ERROR';
export const READ_CARD = 'READ_CARD';
export const READ_CARD_ERROR = 'READ_CARD_ERROR';
export const SHOW_CARD_LOADING = 'SHOW_CARD_LOADING';
export const HIDE_CARD_LOADING = 'HIDE_CARD_LOADING';
export const CLEAR_CARDLIST = 'CLEAR_CARDLIST';
export const CLEAR_READED_CARD = 'CLEAR_READED_CARD';
export const SHOW_CARD_SAVING = 'SHOW_CARD_SAVING';
export const HIDE_CARD_SAVING = 'HIDE_CARD_SAVING';

// learn
export const GET_CARDS_TO_LEARN = 'GET_CARDS_TO_LEARN';
export const GET_CARDS_TO_LEARN_ERROR = 'GET_CARDS_TO_LEARN';
export const SHOW_CARD_ANSWER = 'SHOW_CARD_ANSWER';
export const HIDE_CARD_ANSWER = 'HIDE_CARD_ANSWER';
export const GET_DECK_TO_LEARN = 'GET_DECK_TO_LEARN';
export const GET_DECK_TO_LEARN_ERROR = 'GET_DECK_TO_LEARN_ERROR';
export const CLEAR_DECK_TO_LEARN = 'CLEAR_DECK_TO_LEARN';
export const CLEAR_CARDS_TO_LEARN = 'CLEAR_CARDS_TO_LEARN';
export const SHOW_LEARN_SAVING = 'SHOW_LEARN_SAVING';
export const HIDE_LEARN_SAVING = 'HIDE_LEARN_SAVING';

