// auth
export const SIGNIN = 'SIGNIN';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNOUT = 'SIGNOUT';

export const SHOW_SIGNIN_FORM = 'SHOW_SIGNIN_FORM';
export const SHOW_SIGNUP_FORM = 'SHOW_SIGNUP_FORM';

// user
export const SIGNUP = 'SIGNUP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// deck
export const GET_DECKLIST = 'GET_DECKLIST';
export const GET_DECKLIST_ERROR = 'GET_DECKLIST_ERROR';
export const CREATE_DECK = 'CREATE_DECK';
export const CREATE_DECK_ERROR = 'CREATE_DECK_ERROR';
export const DELETE_DECK = 'DELETE_DECK';
export const DELETE_DECK_ERROR = 'DELETE_DECK_ERROR';
export const READ_DECK = 'READ_DECK';

// card 
export const CREATE_CARD = 'CREATE_CARD';
export const CREATE_CARD_ERROR = 'CREATE_CARD_ERROR';
export const GET_CARDLIST = 'GET_CARDLIST';
export const GET_CARDLIST_ERROR = 'GET_CARDLIST_ERROR';
export const UPDATE_CARD = 'UPDATE_CARD';
export const UPDATE_CARD_ERROR = 'UPDATE_CARD_ERROR';
export const DELETE_CARD = 'DELETE_CARD';
export const DELETE_CARD_ERROR = 'DELETE_CARD_ERROR';

// learn
export const GET_CARDS_TO_LEARN = 'GET_CARDS_TO_LEARN';
export const GET_CARDS_TO_LEARN_ERROR = 'GET_CARDS_TO_LEARN';
// export const UPDATE_THE_EASY_CARD = 'SAVE_THE_EASY_CARD';
// export const UPDATE_THE_NORMAL_CARD = 'SAVE_THE_NORMAL_CARD';
// export const UPDATE_THE_DIFFICULT_CARD = 'SAVE_THE_HARD_CARD';
// export const UPDATE_THE_FORGOTTEN_CARD = 'SAVE_THE_SUPERHARD_CARD';
export const SHOW_CARD_ANSWER = 'SHOW_CARD_ANSWER';
export const HIDE_CARD_ANSWER = 'HIDE_CARD_ANSWER';

